## set echo set
create header, and fill the file after shuffle
``` 
     head -1 usa_00002.csv | awk -F ',' 'BEGIN{OFS=",";} {print $7,$44,$22}' > e.csv
     tail -n+2  usa_00002.csv | gshuf | awk -F ',' 'BEGIN{OFS=",";} {print $7,$44,$22}' >> e.csv
 ```

In [20]:
import pandas as pd

import matplotlib
import matplotlib.pyplot as plt

#from matplotlib.pyplot import figure

print("matplotlib version: {}".format(matplotlib.__version__))
import mglearn
print("mglearn version: {}".format(mglearn.__version__))

#read the data file
path = './e.csv'
%time df = pd.read_csv(path)

states = pd.read_csv("/FIPS.csv")

matplotlib version: 2.2.2
mglearn version: 0.1.6
CPU times: user 904 ms, sys: 205 ms, total: 1.11 s
Wall time: 912 ms

In [21]:
df

         STATEFIP   INCTOT  FAMSIZE
0               8    46600        2
1              48    21000        1
2              48     5300        2
3              37    12300        1
4              48    21500        4
5               5        0        1
6               6    33700        2
7              12    30000        4
8              48  9999999        4
9              47        0        2
10             48        0        5
11             29    12000        5
12             53    24000        8
13             48  9999999        5
14              6   100000        4
15             53     4830        2
16             36    30600        2
17             12        0       13
18             36    26000        1
19             18    36000        2
20             29     4300        2
21             48  9999999        3
22              6        0        5
23              6    40000        7
24             48    30300        4
25             12        0        2
26             36     1900        1
27              9    38000        4
28             34    20700        1
29              6    16000        1
...           ...      ...      ...
3156457        48        0        1
3156458        27    80000        3
3156459         6        0        1
3156460        18    15000        4
3156461        12    35000        4
3156462        34    70000        7
3156463        48    52000        2
3156464         4    10000        2
3156465        12    36000        1
3156466        12    35000        1
3156467        41    85050        2
3156468        27    22000        4
3156469        24    28500        1
3156470        48   215000        2
3156471        51     5900        1
3156472        32     4200        3
3156473        13     4000        5
3156474         6  9999999        7
3156475        18    20000        3
3156476        48        0        1
3156477         9    65000        1
3156478         8    41740        1
3156479        12    10000        4
3156480        22    60000        1
3156481        16    37000        3
3156482        25    95000        5
3156483        26    13500        2
3156484        42    54000        2
3156485        46    34610        2
3156486        36      800        4

[3156487 rows x 3 columns]

In [42]:
# Shows averages per state
df = df[(df.INCTOT < 9999999) & (df.INCTOT !=0) ]
df.groupby(df.STATEFIP).mean()

                INCTOT   FAMSIZE
STATEFIP
1         37737.017404  2.496513
2         39315.688723  3.231188
4         42130.305618  2.678925
5         34966.792488  2.524678
6         51546.729524  2.956305
8         49514.088319  2.564672
9         59812.380191  2.580051
10        47340.526122  2.576889
11        70425.451973  2.066987
12        43500.619911  2.513676
13        43190.745697  2.634462
15        46826.376305  3.260224
16        36939.567618  2.725260
17        46755.600571  2.664027
18        38016.326697  2.563161
19        38721.841928  2.485693
20        40021.999905  2.525196
21        38556.555176  2.522895
22        39223.085161  2.510838
23        38037.054581  2.391093
24        56440.602280  2.716746
25        54268.010825  2.559891
26        39899.977763  2.566412
27        44929.018812  2.568107
28        34650.941599  2.587279
29        38960.062801  2.539889
30        38465.552849  2.496791
31        39862.911430  2.529875
32        43112.575469  2.662268
33        47417.232420  2.509366
34        57959.584591  2.816725
35        36974.820162  2.669136
36        50292.751832  2.728851
37        41527.478002  2.511403
38        44733.556437  2.455374
39        40161.624814  2.521839
40        36639.257786  2.584346
41        42905.035810  2.494373
42        41709.249865  2.565998
44        45848.193840  2.452622
45        39501.028662  2.471393
46        38774.598371  2.555138
47        39480.584000  2.543377
48        45895.029536  2.790463
49        42442.130611  3.156672
50        40704.761142  2.443706
51        52780.180785  2.606993
53        49125.314985  2.586518
54        35195.532827  2.425958
55        40382.791806  2.536186
56        40303.748773  2.582379